development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: postgres
  password: makeanapp
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: postgres
  password: makeanapp